# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.srcs/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz.xci
# IP: The module: 'clk_100Mhz_to_10Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.gen/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_100Mhz_to_10Mhz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.gen/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_100Mhz_to_10Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.gen/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_100Mhz_to_10Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.srcs/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz.xci
# IP: The module: 'clk_100Mhz_to_10Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.gen/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_100Mhz_to_10Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.gen/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_100Mhz_to_10Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/hlocal/RISC-V_Multiciclo_A2YModoDepuracion/RISC-V_Multiciclo_A2YModoDepuracion.gen/sources_1/ip/clk_100Mhz_to_10Mhz/clk_100Mhz_to_10Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_100Mhz_to_10Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
